// Implementation file for parser generated by fsyacc
#light
#nowarn "64";; // turn off warnings that type variables used in production annotations are instantiated to concrete type
open Microsoft.FSharp.Text.Lexing
open Microsoft.FSharp.Text.Parsing.ParseHelpers
# 1 "FSYacc.fsy"

open Tim.Lisp.Core

# 10 "FSYacc.fs"
// This type is the type of tokens accepted by the parser
type token = 
  | LeftParen
  | RightParen
  | Eof
  | Digits of (int)
  | Text of (string)
  | Identifier of (string)
// This type is used to give symbolic names to token indexes, useful for error messages
type tokenId = 
    | TOKEN_LeftParen
    | TOKEN_RightParen
    | TOKEN_Eof
    | TOKEN_Digits
    | TOKEN_Text
    | TOKEN_Identifier
    | TOKEN_end_of_input
    | TOKEN_error
// This type is used to give symbolic names to token indexes, useful for error messages
type nonTerminalId = 
    | NONTERM__startparse
    | NONTERM_Expr
    | NONTERM_ExprList
    | NONTERM_parse

// This function maps tokens to integers indexes
let tagOfToken (t:token) = 
  match t with
  | LeftParen  -> 0 
  | RightParen  -> 1 
  | Eof  -> 2 
  | Digits _ -> 3 
  | Text _ -> 4 
  | Identifier _ -> 5 

// This function maps integers indexes to symbolic token ids
let tokenTagToTokenId (tokenIdx:int) = 
  match tokenIdx with
  | 0 -> TOKEN_LeftParen 
  | 1 -> TOKEN_RightParen 
  | 2 -> TOKEN_Eof 
  | 3 -> TOKEN_Digits 
  | 4 -> TOKEN_Text 
  | 5 -> TOKEN_Identifier 
  | 8 -> TOKEN_end_of_input
  | 6 -> TOKEN_error
  | _ -> failwith "tokenTagToTokenId: bad token"

/// This function maps production indexes returned in syntax errors to strings representing the non terminal that would be produced by that production
let prodIdxToNonTerminal (prodIdx:int) = 
  match prodIdx with
    | 0 -> NONTERM__startparse 
    | 1 -> NONTERM_Expr 
    | 2 -> NONTERM_Expr 
    | 3 -> NONTERM_Expr 
    | 4 -> NONTERM_Expr 
    | 5 -> NONTERM_ExprList 
    | 6 -> NONTERM_ExprList 
    | 7 -> NONTERM_parse 
    | _ -> failwith "prodIdxToNonTerminal: bad production index"

let _fsyacc_endOfInputTag = 8 
let _fsyacc_tagOfErrorTerminal = 6

// This function gets the name of a token as a string
let token_to_string (t:token) = 
  match t with 
  | LeftParen  -> "LeftParen" 
  | RightParen  -> "RightParen" 
  | Eof  -> "Eof" 
  | Digits _ -> "Digits" 
  | Text _ -> "Text" 
  | Identifier _ -> "Identifier" 

// This function gets the data carried by a token as an object
let _fsyacc_dataOfToken (t:token) = 
  match t with 
  | LeftParen  -> (null : System.Object) 
  | RightParen  -> (null : System.Object) 
  | Eof  -> (null : System.Object) 
  | Digits _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | Text _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | Identifier _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
let _fsyacc_gotos = [| 0us; 65535us; 4us; 65535us; 0us; 8us; 5us; 8us; 6us; 10us; 9us; 10us; 2us; 65535us; 0us; 9us; 5us; 6us; 1us; 65535us; 0us; 1us; |]
let _fsyacc_sparseGotoTableRowOffsets = [|0us; 1us; 6us; 9us; |]
let _fsyacc_stateToProdIdxsTableElements = [| 1us; 0us; 1us; 0us; 1us; 1us; 1us; 2us; 1us; 3us; 1us; 4us; 2us; 4us; 6us; 1us; 4us; 1us; 5us; 2us; 6us; 7us; 1us; 6us; 1us; 7us; |]
let _fsyacc_stateToProdIdxsTableRowOffsets = [|0us; 2us; 4us; 6us; 8us; 10us; 12us; 15us; 17us; 19us; 22us; 24us; |]
let _fsyacc_action_rows = 12
let _fsyacc_actionTableElements = [|4us; 32768us; 0us; 5us; 3us; 4us; 4us; 3us; 5us; 2us; 0us; 49152us; 0us; 16385us; 0us; 16386us; 0us; 16387us; 4us; 32768us; 0us; 5us; 3us; 4us; 4us; 3us; 5us; 2us; 5us; 32768us; 0us; 5us; 1us; 7us; 3us; 4us; 4us; 3us; 5us; 2us; 0us; 16388us; 0us; 16389us; 5us; 32768us; 0us; 5us; 2us; 11us; 3us; 4us; 4us; 3us; 5us; 2us; 0us; 16390us; 0us; 16391us; |]
let _fsyacc_actionTableRowOffsets = [|0us; 5us; 6us; 7us; 8us; 9us; 14us; 20us; 21us; 22us; 28us; 29us; |]
let _fsyacc_reductionSymbolCounts = [|1us; 1us; 1us; 1us; 3us; 1us; 2us; 2us; |]
let _fsyacc_productionToNonTerminalTable = [|0us; 1us; 1us; 1us; 1us; 2us; 2us; 3us; |]
let _fsyacc_immediateActions = [|65535us; 49152us; 16385us; 16386us; 16387us; 65535us; 65535us; 16388us; 16389us; 65535us; 16390us; 16391us; |]
let _fsyacc_reductions ()  =    [| 
# 105 "FSYacc.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : Tim.Lisp.Core.LispVal list)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                      raise (Microsoft.FSharp.Text.Parsing.Accept(Microsoft.FSharp.Core.Operators.box _1))
                   )
                 : '_startparse));
# 114 "FSYacc.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 14 "FSYacc.fsy"
                      Atom _1 
                   )
# 14 "FSYacc.fsy"
                 : 'Expr));
# 125 "FSYacc.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 15 "FSYacc.fsy"
                      String _1 
                   )
# 15 "FSYacc.fsy"
                 : 'Expr));
# 136 "FSYacc.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : int)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 16 "FSYacc.fsy"
                      Number _1 
                   )
# 16 "FSYacc.fsy"
                 : 'Expr));
# 147 "FSYacc.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'ExprList)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 17 "FSYacc.fsy"
                      _2 |> List.rev |> List 
                   )
# 17 "FSYacc.fsy"
                 : 'Expr));
# 158 "FSYacc.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'Expr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 19 "FSYacc.fsy"
                      [ _1 ] 
                   )
# 19 "FSYacc.fsy"
                 : 'ExprList));
# 169 "FSYacc.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'ExprList)) in
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'Expr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 20 "FSYacc.fsy"
                      _2 :: _1  
                   )
# 20 "FSYacc.fsy"
                 : 'ExprList));
# 181 "FSYacc.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'ExprList)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 22 "FSYacc.fsy"
                      List.rev _1 
                   )
# 22 "FSYacc.fsy"
                 : Tim.Lisp.Core.LispVal list));
|]
# 193 "FSYacc.fs"
let tables () : Microsoft.FSharp.Text.Parsing.Tables<_> = 
  { reductions= _fsyacc_reductions ();
    endOfInputTag = _fsyacc_endOfInputTag;
    tagOfToken = tagOfToken;
    dataOfToken = _fsyacc_dataOfToken; 
    actionTableElements = _fsyacc_actionTableElements;
    actionTableRowOffsets = _fsyacc_actionTableRowOffsets;
    stateToProdIdxsTableElements = _fsyacc_stateToProdIdxsTableElements;
    stateToProdIdxsTableRowOffsets = _fsyacc_stateToProdIdxsTableRowOffsets;
    reductionSymbolCounts = _fsyacc_reductionSymbolCounts;
    immediateActions = _fsyacc_immediateActions;
    gotos = _fsyacc_gotos;
    sparseGotoTableRowOffsets = _fsyacc_sparseGotoTableRowOffsets;
    tagOfErrorTerminal = _fsyacc_tagOfErrorTerminal;
    parseError = (fun (ctxt:Microsoft.FSharp.Text.Parsing.ParseErrorContext<_>) -> 
                              match parse_error_rich with 
                              | Some f -> f ctxt
                              | None -> parse_error ctxt.Message);
    numTerminals = 9;
    productionToNonTerminalTable = _fsyacc_productionToNonTerminalTable  }
let engine lexer lexbuf startState = (tables ()).Interpret(lexer, lexbuf, startState)
let parse lexer lexbuf : Tim.Lisp.Core.LispVal list =
    Microsoft.FSharp.Core.Operators.unbox ((tables ()).Interpret(lexer, lexbuf, 0))
